import { Nav } from "./(components)/(nav)/Nav";
import "./globals.css";
import { Nunito } from "next/font/google";
import { ContextProvider } from "../context";

const nunito = Nunito({ subsets: ["latin"] });
// Nunito;
// Rubik;
// Poppins;
// Outfit;
// Varela Round
// Karla;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ContextProvider>
          <div className={`flex min-h-screen flex-col`}>
            <Nav />
            <main className="grow">
              <div className="flex min-h-[calc(100vh-8rem)] flex-col justify-center">
                {/* <div className="flex min-h-[calc(100vh-8rem)] flex-col items-center justify-center space-y-4"> */}
                {children}
              </div>
            </main>
            <div className="h-16"></div>
          </div>
        </ContextProvider>
        {/*
        <Script
          async
          src="https://analytics.umami.is/script.js"
          data-website-id="9c19606f-729d-4e2e-a8b3-75e9667ec2a3"
        /> */}
      </body>
    </html>
  );
}
