CREATE TABLE public.words (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word text NOT NULL UNIQUE,
    rating real DEFAULT 1200 NOT NULL,
    wins integer DEFAULT 0 NOT NULL,
    losses integer DEFAULT 0 NOT NULL
);

CREATE TABLE public.matches (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    choice_1 smallint NOT NULL REFERENCES public.words(id),
    choice_2 smallint NOT NULL REFERENCES public.words(id),
    winner smallint NOT NULL REFERENCES public.words(id)
);

-- Elo update with K = 32, ratings rounded to one decimal place.
CREATE OR REPLACE FUNCTION public.handle_match(
    choice_1_input integer,
    choice_2_input integer,
    winner_id_input integer
) RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    loser_id integer;
    winner_rating real;
    loser_rating real;
    winner_exp double precision;
BEGIN
    IF choice_1_input = choice_2_input
        OR winner_id_input NOT IN (choice_1_input, choice_2_input) THEN
        RAISE EXCEPTION 'invalid match: % vs % won by %',
            choice_1_input, choice_2_input, winner_id_input;
    END IF;

    loser_id := CASE WHEN winner_id_input = choice_1_input
        THEN choice_2_input ELSE choice_1_input END;

    -- Lock both rows in id order so concurrent votes on the same words serialise without deadlocking.
    PERFORM 1 FROM words WHERE id IN (winner_id_input, loser_id) ORDER BY id FOR UPDATE;

    SELECT rating INTO winner_rating FROM words WHERE id = winner_id_input;
    SELECT rating INTO loser_rating FROM words WHERE id = loser_id;

    IF winner_rating IS NULL OR loser_rating IS NULL THEN
        RAISE EXCEPTION 'unknown word id in match % vs %', choice_1_input, choice_2_input;
    END IF;

    winner_exp := 1 / (1 + power(10, (loser_rating - winner_rating) / 400.0));

    INSERT INTO matches (choice_1, choice_2, winner)
    VALUES (choice_1_input, choice_2_input, winner_id_input);

    UPDATE words
    SET rating = round((winner_rating + 32 * (1 - winner_exp))::numeric, 1),
        wins = wins + 1
    WHERE id = winner_id_input;

    UPDATE words
    SET rating = round((loser_rating - 32 * (1 - winner_exp))::numeric, 1),
        losses = losses + 1
    WHERE id = loser_id;
END;
$$;
